version: "2"
services:

  web:
    container_name: Stark_ITG_CRM
    build: .
    ports:
      - 8835:8080
    restart: always
    networks:
      app_net:
        ipv4_address: 10.1.23.2
    environment:
      CATALINA_OPTS: -Dspring.config.location=/usr/local/tomcat/application-itg.properties 
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.23.0/24
        gateway: 10.1.23.1