version: "2"
services:

  web:
    container_name: CRM-module-preprod
    build: .
    ports:
      - 8787:8080
    networks:
      app_net:
        ipv4_address: 10.1.44.2
    environment:
      CATALINA_OPTS: -Dspring.config.location=/usr/local/tomcat/application-preprod.properties  
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.44.0/24
        gateway: 10.1.44.1
